# Generated by Django 4.2.7 on 2023-12-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_taskmodel_assign_date'),
        ('category', '0004_remove_categorymodel_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='task',
            field=models.ManyToManyField(to='task.taskmodel'),
        ),
    ]
