# Generated by Django 4.2.7 on 2023-12-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_remove_categorymodel_task'),
        ('task', '0002_alter_taskmodel_assign_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category',
            field=models.ManyToManyField(to='category.categorymodel'),
        ),
    ]
